import Head from "next/head";
import { AiOutlineShoppingCart } from "react-icons/ai";
import axios from "axios";
import { useState, useEffect } from "react";
import Image from "next/image";
import Link from "next/link";
import ProductCard from "../components/ProductCard";
import Footer from "../components/Footer/Footer";

export default function Home({ products }) {
  return (
    <div>
      <Head>
        <title>Fudo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ProductCard data={products} />
      <Footer />
    </div>
  );
}

export const getServerSideProps = async () => {
  const { data } = await axios.get("http://localhost:3000/api/products");
  return {
    props: {
      products: data,
    },
  };
};
